# Generated by Django 5.2.5 on 2025-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_playlist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('can_Bulk_upload_', 'Can bulk upload books')]},
        ),
        migrations.AlterField(
            model_name='books',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='taged_books', to='books.tag'),
        ),
    ]
