# Generated by Django 5.2.5 on 2025-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_options_alter_books_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
