# Generated by Django 5.2.5 on 2025-10-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
