# Generated by Django 5.2.5 on 2025-10-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_tag_update_date_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='uploader',
        ),
    ]
